/* Physics JRF Journey V5.9.2 — post-implementation review + UX hardening */
(()=>{
'use strict';
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const norm=raw=>{if(Array.isArray(raw?.topics))return raw.topics;if(Array.isArray(raw?.records))return raw.records;const out=[];for(const s of Array.isArray(raw?.subjects)?raw.subjects:[])for(const t of Array.isArray(s?.topics)?s.topics:[])out.push({...t,subject_id:t.subject_id??s.id,subject:t.subject??s.name});return out};
const topics=()=>norm(window.data||{});
const qs=()=>Array.isArray(window.questions)?window.questions:[];
const tid=t=>String(t?.id??t?.topic_id??t?.topicId??'');
const tname=t=>String(t?.topic??t?.name??t?.title??'Topic');
const words=v=>{if(v==null)return 0;const x=Array.isArray(v)?v.join(' '):typeof v==='object'?Object.values(v).join(' '):String(v);return x.trim()?x.trim().split(/\s+/).length:0};
const text=v=>{if(v==null)return '';if(Array.isArray(v))return v.map(text).join(' ');if(typeof v==='object')return Object.values(v).map(text).join(' ');return String(v)};
const qFor=t=>qs().filter(q=>String(q.topic_id)===tid(t));
const stats=t=>{const b=window.state?.byTopic||{},x=b[tid(t)]||{},a=Number(x.attempts||0),c=Number(x.correct||0);return{attempts:a,correct:c,accuracy:a?c/a:0,mastered:!!x.mastered}};
function installStyle(){if(document.getElementById('v592-style'))return;const s=document.createElement('style');s.id='v592-style';s.textContent=`
#v592-loader{position:fixed;inset:0;z-index:10000;background:rgba(244,246,251,.97);display:grid;place-items:center}.v592-load{width:min(460px,calc(100vw - 32px));background:#fff;border:1px solid var(--line);border-radius:20px;padding:25px;box-shadow:0 20px 60px #1b25521c}.v592-load h2{margin:0 0 6px}.v592-track{height:9px;background:#e6e9f0;border-radius:99px;overflow:hidden;margin:16px 0 8px}.v592-track i{display:block;height:100%;width:0;background:var(--brand);transition:width .2s}.v592-percent{font-weight:900}.v592-skeleton{display:grid;gap:10px}.v592-skeleton i{display:block;height:54px;border-radius:12px;background:linear-gradient(90deg,#eef1f6,#f8f9fb,#eef1f6);background-size:200% 100%;animation:v592sk 1.2s infinite}@keyframes v592sk{to{background-position:-200% 0}}.v592-error{position:fixed;inset:0;z-index:10001;display:grid;place-items:center;background:#11172bd9;padding:18px}.v592-error-card{width:min(520px,100%);background:#fff;border-radius:18px;padding:24px}.v592-error-card h2{color:var(--red)}.v592-topic-meta{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:9px}.v592-progress{height:7px;background:#e6e9f0;border-radius:99px;overflow:hidden;margin-top:8px}.v592-progress i{display:block;height:100%;background:var(--brand)}.v592-diff-easy{background:#e8f7f1!important;color:#14815d!important}.v592-diff-moderate{background:#fff3db!important;color:#a46700!important}.v592-diff-hard{background:#fff0f2!important;color:#b63e50!important}.v592-review{margin-top:18px}.v592-review table{width:100%;border-collapse:collapse}.v592-review th,.v592-review td{padding:8px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}.v592-grade{font-size:28px;font-weight:900}.v592-gap{color:var(--red);font-weight:800}.v592-ok{color:var(--green);font-weight:800}.v592-score{font-weight:900}.v592-report-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.v592-report-card{border:1px solid var(--line);border-radius:12px;padding:13px;background:var(--card)}
@media(max-width:900px){.v592-report-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:680px){.v592-report-grid{grid-template-columns:1fr}.v592-review{overflow:auto}.v592-review table{min-width:720px}}
`;document.head.appendChild(s)}
function loading(){if(document.getElementById('v592-loader'))return;const d=document.createElement('div');d.id='v592-loader';d.innerHTML='<div class="v592-load"><h2>Opening Physics JRF Journey</h2><div class="muted">Preparing your study content and practice bank…</div><div class="v592-track"><i id="v592-load-bar"></i></div><div><span id="v592-load-pct" class="v592-percent">0%</span> <span id="v592-load-msg" class="muted">Starting…</span></div><div class="muted" style="margin-top:8px">Usually &lt;3 seconds</div><div id="v592-skeletons" class="v592-skeleton" style="margin-top:14px"><i></i><i></i><i></i></div></div>';document.body.appendChild(d);let p=0;const timer=setInterval(()=>{if(window.__PJR_DATA_READY){p=Math.max(p,100);clearInterval(timer)}else p=Math.min(p+7,92);const b=document.getElementById('v592-load-bar'),n=document.getElementById('v592-load-pct');if(b)b.style.width=p+'%';if(n)n.textContent=p+'%';if(++loading.ticks>40){clearInterval(timer);showError('The study data did not finish loading within 10 seconds.')}} ,120)}loading.ticks=0;
function finish(){const d=document.getElementById('v592-loader');if(!d)return;const b=document.getElementById('v592-load-bar'),n=document.getElementById('v592-load-pct'),m=document.getElementById('v592-load-msg');if(b)b.style.width='100%';if(n)n.textContent='100%';if(m)m.textContent='Ready';setTimeout(()=>d.remove(),180)}
function showError(message){if(document.getElementById('v592-error'))return;document.getElementById('v592-loader')?.remove();const d=document.createElement('div');d.id='v592-error';d.className='v592-error';d.innerHTML=`<div class="v592-error-card"><h2>Failed to load Study Content</h2><p>${esc(message)}</p><p class="muted">The portal could not prepare the study data. Please retry after the deployment has completed.</p><button class="btn" id="v592-retry">↻ Retry</button></div>`;document.body.appendChild(d);document.getElementById('v592-retry').onclick=()=>location.reload()}
function dashboard(){const h=document.getElementById('homekpis');if(!h||!window.__PJR_DATA_READY)return;const ts=topics(),b=window.state?.byTopic||{};let attempts=0,correct=0;Object.values(b).forEach(x=>{attempts+=Number(x?.attempts||0);correct+=Number(x?.correct||0)});const mastered=ts.filter(t=>stats(t).mastered).length,mastery=ts.length?Math.round(mastered/ts.length*100):0,accuracy=attempts?Math.round(correct/attempts*100):0;h.innerHTML=`<div class="card"><div class="muted">Overall Mastery</div><div class="stat">${mastery}%</div><div class="muted">${mastered} of ${ts.length} topics</div><div class="v592-progress"><i style="width:${mastery}%"></i></div></div><div class="card"><div class="muted">Questions Attempted</div><div class="stat">${attempts}</div><div class="muted">Across all practice sessions</div></div><div class="card"><div class="muted">Accuracy</div><div class="stat">${accuracy}%</div><div class="muted">${correct} correct of ${attempts} attempted</div></div><div class="card"><div class="muted">Study Topics</div><div class="stat">${ts.length}</div><div class="muted">Merged study curriculum</div></div>`}
function decorateTopics(){const ts=topics();document.querySelectorAll('#topiclist .topic').forEach(el=>{if(el.dataset.v592)return;el.dataset.v592='1';const txt=el.textContent||'',t=ts.find(x=>txt.includes(tname(x)));if(!t)return;const st=stats(t),pct=st.mastered?100:Math.round((st.attempts?st.accuracy*.75+Math.min(st.attempts,8)/8*.25:0)*100);const m=document.createElement('div');m.className='v592-topic-meta';m.innerHTML=`<span class="tag">${st.mastered?'● Mastered':st.attempts?'◐ In Progress':'○ Not started'}</span><span class="muted">${pct}% mastery</span>`;el.appendChild(m);const p=document.createElement('div');p.className='v592-progress';p.innerHTML=`<i style="width:${pct}%"></i>`;el.appendChild(p)})}
function decorateQuestions(){document.querySelectorAll('.q,.qhead,.badge,.tag').forEach(el=>{if(el.dataset.v592)return;const tx=(el.textContent||'').trim().toLowerCase();if(tx==='easy'||tx.includes('easy'))el.classList.add('v592-diff-easy');if(tx==='moderate'||tx.includes('moderate'))el.classList.add('v592-diff-moderate');if(tx==='hard'||tx.includes('hard'))el.classList.add('v592-diff-hard');el.dataset.v592='1'})}
const critical=[['Schrödinger Equation',['schrodinger']],['Harmonic Oscillator',['harmonic oscillator']],['Hydrogen Atom',['hydrogen atom']],['Perturbation Theory',['perturbation']],['Angular Momentum & Spin',['angular momentum','spin']],['Multielectron Atoms',['multielectron','multi-electron']],['Coulomb\'s Law & Fields',['coulomb']],['Gauss\'s Law',['gauss']],['Maxwell\'s Equations',['maxwell']],['EM Waves',['electromagnetic wave','em wave']],['Radiation & Dipole',['radiation','dipole']],['First Law of Thermodynamics',['first law','thermodynamics']],['Entropy & Second Law',['entropy','second law']],['Partition Function',['partition function']],['Fermi-Dirac & Bose-Einstein Statistics',['fermi-dirac','bose-einstein']],['Ideal Gas & Applications',['ideal gas']],['Newton\'s Laws & Dynamics',['newton']],['Oscillations',['oscillation']],['Lagrangian & Hamiltonian Mechanics',['lagrangian','hamiltonian']],['Crystal Structure',['crystal structure','bravais']],['X-ray Diffraction',['x-ray','bragg']],['Band Structure & Semiconductors',['band structure','semiconductor']],['Basic Electronics',['diode','transistor']],['Op-Amps & Circuits',['op-amp','operational amplifier']],['Experimental Techniques',['experimental technique','error analysis','oscilloscope','spectroscopy']]];
function scoreTopic(t){const raw=text(t).toLowerCase(),qsx=qFor(t),exampleWords=words(t.worked_example)+words(t.worked_example_detail);const conceptual=['overview','learning_objectives','syllabus_points','concepts'].filter(k=>words(t[k])>0).length;const c1=Math.min(5,Math.max(1,conceptual+1));const math=/(derive|derivation|integrat|differentiat|eigen|commutator|lagrang|hamilton|equation)/i.test(raw)&&words(t.formula_focus)>0?5:words(t.formula_focus)>0?3:2;const ex=exampleWords>=500?5:exampleWords>=250?4:exampleWords>=100?3:exampleWords>=25?2:1;const visual=/(diagram|figure|plot|graph|schematic|visual)/i.test(raw)?4:1;const practice=qsx.length>=12?5:qsx.length>=8?4:qsx.length>=5?3:qsx.length>=3?2:1;const connections=(words(t.resources)>0?1:0)+(words(t.revision)>0?1:0)+(words(t.pyq_mapping)>0?1:0)+(words(t.common_mistakes)>0?1:0)+(/(application|advanced|extension|related)/i.test(raw)?1:0);const conn=Math.min(5,Math.max(1,connections));const avg=+((c1+math+ex+visual+practice+conn)/6).toFixed(1);const gaps=[];if(math<3)gaps.push('Missing/weak derivation');if(ex<3)gaps.push('Fewer than 3 worked examples');if(visual<3)gaps.push('No meaningful diagrams/plots detected');if(practice<3)gaps.push('Fewer than 5 practice questions');if(conn<3)gaps.push('Limited connections/extensions');return{avg,c1,math,ex,visual,practice,conn,gaps,q:qsx.length}}
function findTopic(spec){const ts=topics();return ts.find(t=>{const n=tname(t).toLowerCase();return spec[1].some(k=>n.includes(k))})}
function review(){const a=document.getElementById('analytics');if(!a||document.getElementById('v592-review'))return;const rows=critical.map(([label,keys])=>{const t=findTopic([label,keys]);if(!t)return `<tr><td><b>${esc(label)}</b></td><td colspan="7" class="v592-gap">Not found in merged curriculum</td></tr>`;const s=scoreTopic(t);return `<tr><td><b>${esc(label)}</b></td><td>${s.avg}/5</td><td>${s.c1}</td><td>${s.math}</td><td>${s.ex}</td><td>${s.visual}</td><td>${s.practice} (${s.q})</td><td>${s.conn}</td><td>${s.gaps.length?s.gaps.map(esc).join('; '):'<span class="v592-ok">Strong</span>'}</td></tr>`}).join('');const ts=topics(),avg=ts.length?ts.reduce((sum,t)=>sum+scoreTopic(t).avg,0)/ts.length:0;const practiced=ts.filter(t=>qFor(t).length>=5).length;const visuals=ts.filter(t=>/(diagram|figure|plot|graph|schematic|visual)/i.test(text(t))).length;const criticalAvg=critical.map(([l,k])=>findTopic([l,k])).filter(Boolean).map(scoreTopic);const qm=criticalAvg.slice(0,6).length?criticalAvg.slice(0,6).reduce((x,s)=>x+s.avg,0)/criticalAvg.slice(0,6).length:0;const box=document.createElement('div');box.id='v592-review';box.className='section card v592-review';box.innerHTML=`<div class="top"><div><h2 style="margin:0">🔍 V5.9.2 Post-Implementation Review</h2><p class="muted">Automated self-assessment against the requested UI/UX and study-depth framework.</p></div><span class="pill">${new Date().toLocaleDateString()}</span></div><div class="v592-report-grid"><div class="v592-report-card"><div class="muted">Topic depth average</div><div class="v592-grade">${avg.toFixed(1)}/5</div></div><div class="v592-report-card"><div class="muted">Topics ≥5 questions</div><div class="v592-grade">${practiced}/${ts.length}</div></div><div class="v592-report-card"><div class="muted">Topics with visual signals</div><div class="v592-grade">${visuals}/${ts.length}</div></div><div class="v592-report-card"><div class="muted">QM critical average</div><div class="v592-grade">${qm.toFixed(1)}/5</div></div></div><h3>Critical-topic scorecards</h3><div style="overflow:auto"><table><thead><tr><th>Topic</th><th>Avg</th><th>Concept</th><th>Math</th><th>Examples</th><th>Visuals</th><th>Practice</th><th>Connections</th><th>Gaps</th></tr></thead><tbody>${rows}</tbody></table></div><p class="muted" style="margin-bottom:0">Scores are evidence-based from the merged topic metadata and question bank. Visual scores require explicit diagram/plot/figure signals; they are not inferred from CSS cards.</p>`;a.appendChild(box)}
function boot(){installStyle();loading();const ready=e=>{if(!e?.detail?.topics&& !window.__PJR_DATA_READY)return;finish();dashboard();decorateTopics();decorateQuestions();review();const obs=new MutationObserver(()=>{dashboard();decorateTopics();decorateQuestions()});obs.observe(document.querySelector('main')||document.body,{childList:true,subtree:true});setTimeout(review,700)};if(window.__PJR_DATA_READY)ready({detail:window.__PJR_DATA_READY});window.addEventListener('pjr:data-ready',ready);setTimeout(()=>{if(!window.__PJR_DATA_READY&&!document.getElementById('v592-error'))showError('The study data did not finish loading within 10 seconds.')},10500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
