/* Physics JRF Journey V5.9.2 — safe review layer
   This enhancement must never block application startup. */
(()=>{
'use strict';
const norm=raw=>{if(Array.isArray(raw?.topics))return raw.topics;if(Array.isArray(raw?.records))return raw.records;const out=[];for(const s of Array.isArray(raw?.subjects)?raw.subjects:[])for(const t of Array.isArray(s?.topics)?s.topics:[])out.push({...t,subject_id:t.subject_id??s.id,subject:t.subject??s.name});return out};
const topics=()=>norm(window.data||{});
const qs=()=>Array.isArray(window.questions)?window.questions:[];
const tid=t=>String(t?.id??t?.topic_id??t?.topicId??'');
const tname=t=>String(t?.topic??t?.name??t?.title??'Topic');
const qFor=t=>qs().filter(q=>String(q?.topic_id??q?.topicId??'')===tid(t));
const stats=t=>{const b=window.state?.byTopic||{},x=b[tid(t)]||{},a=Number(x.attempts||0),c=Number(x.correct||0);return{attempts:a,correct:c,accuracy:a?c/a:0,mastered:!!x.mastered}};
function installStyle(){if(document.getElementById('v592-style'))return;const s=document.createElement('style');s.id='v592-style';s.textContent='.v592-topic-meta{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:9px}.v592-progress{height:7px;background:#e6e9f0;border-radius:99px;overflow:hidden;margin-top:8px}.v592-progress i{display:block;height:100%;background:var(--brand)}.v592-review{margin-top:18px}.v592-report-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.v592-report-card{border:1px solid var(--line);border-radius:12px;padding:13px;background:var(--card)}.v592-grade{font-size:28px;font-weight:900}@media(max-width:900px){.v592-report-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:680px){.v592-report-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
/* Non-blocking by design. The previous layer could leave the full-screen “Opening Physics JRF Journey” overlay permanently visible when the data-ready event raced its listener. */
function loading(){}
function finish(){}
function showError(message){console.warn('V5.9.2 review layer:',message)}
function dashboard(){try{const h=document.getElementById('homekpis');if(!h)return;const ts=topics(),b=window.state?.byTopic||{};let attempts=0,correct=0;Object.values(b).forEach(x=>{attempts+=Number(x?.attempts||0);correct+=Number(x?.correct||0)});const mastered=ts.filter(t=>stats(t).mastered).length,mastery=ts.length?Math.round(mastered/ts.length*100):0,accuracy=attempts?Math.round(correct/attempts*100):0;h.innerHTML='<div class="card"><div class="muted">Overall Mastery</div><div class="stat">'+mastery+'%</div><div class="muted">'+mastered+' of '+ts.length+' topics</div><div class="v592-progress"><i style="width:'+mastery+'%"></i></div></div><div class="card"><div class="muted">Questions Attempted</div><div class="stat">'+attempts+'</div><div class="muted">Across all practice sessions</div></div><div class="card"><div class="muted">Accuracy</div><div class="stat">'+accuracy+'%</div><div class="muted">'+correct+' correct of '+attempts+' attempted</div></div><div class="card"><div class="muted">Study Topics</div><div class="stat">'+ts.length+'</div><div class="muted">Merged study curriculum</div></div>'}catch(e){console.warn('V5.9.2 dashboard enhancement skipped',e)}}
function decorateTopics(){try{const ts=topics();document.querySelectorAll('#topiclist .topic').forEach(el=>{if(el.dataset.v592)return;const txt=el.textContent||'',t=ts.find(x=>txt.includes(tname(x)));if(!t)return;el.dataset.v592='1';const st=stats(t),pct=st.mastered?100:Math.round((st.attempts?st.accuracy*.75+Math.min(st.attempts,8)/8*.25:0)*100);const m=document.createElement('div');m.className='v592-topic-meta';m.innerHTML='<span class="tag">'+(st.mastered?'● Mastered':st.attempts?'◐ In Progress':'○ Not started')+'</span><span class="muted">'+pct+'% mastery</span>';el.appendChild(m);const p=document.createElement('div');p.className='v592-progress';p.innerHTML='<i style="width:'+pct+'%"></i>';el.appendChild(p)})}catch(e){console.warn('V5.9.2 topic enhancement skipped',e)}}
function decorateQuestions(){try{document.querySelectorAll('.q,.qhead,.badge,.tag').forEach(el=>{if(el.dataset.v592)return;const tx=(el.textContent||'').trim().toLowerCase();if(tx==='easy'||tx.includes('easy'))el.classList.add('v592-diff-easy');if(tx==='moderate'||tx.includes('moderate'))el.classList.add('v592-diff-moderate');if(tx==='hard'||tx.includes('hard'))el.classList.add('v592-diff-hard');el.dataset.v592='1'})}catch(e){console.warn('V5.9.2 question enhancement skipped',e)}}
function review(){try{const a=document.getElementById('analytics');if(!a||document.getElementById('v592-review'))return;const ts=topics();if(!ts.length)return;const practiced=ts.filter(t=>qFor(t).length>=5).length;const box=document.createElement('div');box.id='v592-review';box.className='section card v592-review';box.innerHTML='<div class="top"><div><h2 style="margin:0">🔍 V5.9.2 Application Review</h2><p class="muted">Runtime health summary from the merged curriculum and question bank.</p></div><span class="pill">Live</span></div><div class="v592-report-grid"><div class="v592-report-card"><div class="muted">Topics</div><div class="v592-grade">'+ts.length+'</div></div><div class="v592-report-card"><div class="muted">Topics ≥5 questions</div><div class="v592-grade">'+practiced+'/'+ts.length+'</div></div><div class="v592-report-card"><div class="muted">Question bank</div><div class="v592-grade">'+qs().length+'</div></div><div class="v592-report-card"><div class="muted">Status</div><div class="v592-grade">Ready</div></div></div>';a.appendChild(box)}catch(e){console.warn('V5.9.2 review enhancement skipped',e)}}
function refresh(){installStyle();dashboard();decorateTopics();decorateQuestions();review()}
function boot(){refresh();window.addEventListener('pjr:data-ready',e=>{try{if(e?.detail)window.__PJR_DATA_READY=e.detail;refresh()}catch(err){console.warn('V5.9.2 data refresh skipped',err)}});setTimeout(refresh,250);setTimeout(refresh,1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
